SistemaLoca/SistemaLoca.WebApp/Controllers/FilmeController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SistemaLoca.BusinnesLogic.Model.ControleAcervo;
using SistemaLoca.BusinnesLogic.Model;
using SistemaLoca.BusinnesLogic.Repositorio;

namespace SistemaLoca.WebApp.Controllers
{ 
    public class FilmeController : Controller
    {
        private UnitOfWork uow = new UnitOfWork();

        //
        // GET: /Filme/

        public ViewResult Index()
        {
            return View(uow.FilmeRepository.GetAll());
        }

        //
        // GET: /Filme/Details/5

        public ViewResult Details(int id)
        {
            Filme filme = uow.FilmeRepository.GetByID(id);
            return View(filme);
        }
        
        //INICIO DO COMBO
        private void PopulateGenerosDropDownList(object selecionado = null)
        {
            IEnumerable<Genero> generos = uow.generoRepository.GetAll();
            ViewData["GeneroID"] = new SelectList(generos, "Id", "descricao", selecionado);
        }
 
        //
        // GET: /Filme/Create

        public ActionResult Create()
        {
            PopulateGenerosDropDownList();

            return View();
        }

        //
        // POST: /Filme/Create

        [HttpPost]
        public ActionResult Create(Filme filme)
        {
            if (ModelState.IsValid)
            {
                uow.FilmeRepository.Insert(filme);
                uow.Save();
                return RedirectToAction("Index");
            }

            PopulateGenerosDropDownList(filme.GeneroID);
            return View(filme);

        }
               
        //
        // GET: /Filme/Edit/5
 
        public ActionResult Edit(int id)
        {
            Filme filme = uow.FilmeRepository.GetByID(id);
            return View(filme);
        }

        //
        // POST: /Filme/Edit/5

        [HttpPost]
        public ActionResult Edit(Filme filme)
        {
            if (ModelState.IsValid)
            {
                uow.FilmeRepository.Update(filme);    
                uow.Save();
                return RedirectToAction("Index");
            }
            return View(filme);
        }

        //
        // GET: /Filme/Delete/5
 
        public ActionResult Delete(int id)
        {
            Filme filme = uow.FilmeRepository.GetByID(id);
            return View(filme);
        }

        //
        // POST: /Filme/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Filme filme = uow.FilmeRepository.GetByID(id);
            uow.FilmeRepository.Delete(filme);
            uow.Save();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            uow.Dispose();
            base.Dispose(disposing);
        }
    }
}

SistemaLoca/SistemaLoca.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
    <script src="@Url.Content("~/Scripts/jquery-1.5.1.min.js")" type="text/javascript"></script>
</head>
<body>
    <div class="page">
        <div id="header">
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <div id="menucontainer">
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Acervo", "Index", "Filme")</li>
                    <li>@Html.ActionLink("ItemFilme", "Index", "ItemFilme")</li>
                    <li>@Html.ActionLink("Genero", "Index", "Genero")</li>
                    <li>@Html.ActionLink("Midia", "Index", "Midia")</li>
                    <li>@Html.ActionLink("Distribuidora", "Index", "Distribuidora")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </div>
        </div>
        <div id="main">
            @RenderBody()
        </div>
        <div id="footer">
        </div>
    </div>
</body>
</html>

SistemaLoca/SistemaLoca.WebApp/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}